---
- name: "Deploy Web Application Stack"
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Install nginx and nodejs 12 Packages"
      ansible.builtin.dnf:
        name: "nginx, @nodejs:12"
        update_cache: true
        state: present
    - name: "Copy over webapp"
      ansible.builtin.copy:
        src: "webapp"
        dest: "/opt"
        mode: "0755"
    - name: "Install NodeJS Dependencies"
      community.general.npm:
        path: "/opt/webapp"
        state: present
    - name: "Install nginx configuration"
      ansible.builtin.copy:
        src: "webapp.config"
        dest: "/etc/nginx/nginx.conf"
        owner: "root"
        group: "root"
        mode: "0644"
    - name: "Set selinux http policy"
      ansible.posix.seboolean:
        name: "httpd_can_network_connect"
        state: false
        persistent: true
    - name: "Start and Enable nginx"
      ansible.builtin.systemd:
        name: "nginx"
        state: restarted
        enabled: true
    - name: "Deploy webapp service unit"
      ansible.builtin.copy:
        src: "webapp.service"
        dest: "/etc/systemd/system"
        owner: "root"
        group: "root"
        mode: "0644"
    - name: "Configure webapp setting"
      ansible.builtin.copy:
        src: "webapp_message.cfg"
        dest: "/opt/webapp/config"
        owner: "root"
        group: "root"
        mode: "0644"
    - name: "Start and Enable webapp"
      ansible.builtin.systemd:
        name: "webapp"
        state: restarted
        enabled: true
        daemon_reload: true
